# Generated by Django 5.0.3 on 2024-03-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_desc',
            new_name='goal_description',
        ),
    ]
